# These settings are synced to GitHub by https://probot.github.io/apps/settings/
_extends: .github

repository:
  name: renovate-issue-aws-ecr-access
  description: ':lady_beetle: As described in the issue [Renovate Issue]https://github.com/renovatebot/renovate/issues/'
  homepage: https://ivankatliarchuk.github.io
  topics: ivka, renovate, renovate-issue, aws
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  has_pages: true
  is_template: true
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: false

branches:
  - name: main
