# https://docs.aws.amazon.com/eks/latest/userguide/managing-coredns.html
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    eks.amazonaws.com/component: coredns
    k8s-app: kube-dns
    kubernetes.io/name: CoreDNS
    team: paas
  name: coredns
  namespace: kube-system
spec:
  revisionHistoryLimit: 3
  replicas: 2
  selector:
    matchLabels:
      eks.amazonaws.com/component: coredns
      k8s-app: kube-dns
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        eks.amazonaws.com/component: coredns
        k8s-app: kube-dns
        team: paas
    spec:
      containers:
        - args:
            - -conf
            - /etc/coredns/Corefile
          image: 602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/coredns:v1.11.3
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
