# https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html
# https://amazon-eks.s3-us-west-2.amazonaws.com/cloudformation/2020-06-10/kube-proxy-daemonset.yaml
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: kube-proxy
    eks.amazonaws.com/component: kube-proxy
    team: paas
  name: kube-proxy
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: kube-proxy
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        k8s-app: kube-proxy
        team: paas
    spec:
      hostNetwork: true
      tolerations:
      - operator: "Exists"
      priorityClassName: system-node-critical
      containers:
      - name: kube-proxy
        image: 602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/kube-proxy:v1.27.4-eksbuild.2
        resources:
          requests:
            cpu: 100m
        command:
        - kube-proxy
        - --v=2
        - --config=/var/lib/kube-proxy-config/config
